baseurl = "https://siori9.github.io/Page-concours-photo-BDA/"
metaDataFormat = "yaml"
title = "Résultat concours photo BDA"
theme = "blist"

DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.fr]
    contentDir = "content/fr" #Français
    weight = 1
    languageName = "Français"
    [languages.fr.params]
      introTitle = "Grand gagnant : Volodia Gromykhov"
      introSubtitle = "Les votes ont été très serré, les jurys ayant donné les mêmes notes aux trois premières photos. Un dernier classement du top 3 a dû être fait, voici le gagnant ! Félicitation à lui !"
      introPhoto = "/photos/19_[VG].jpg"
      logo = "logo-bda.png"
    [[languages.fr.menu.main]]
        name = "Résultat concours photo"
        url = "blog"
        weight = 1

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "BDA 2022 - Divag · Concours photo Novembre"
  favicon = "favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  #  frontBundle = ""

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Suivez-nous"
  description = "N'hésitez pas à suivre le Bureau Des Arts de CY Tech Pau pour profiter de nos nombreux évènements !"
  instagram = "https://www.instagram.com/bda_pau_cytech/"
  youtube = "https://www.youtube.com/channel/UCoXfDddjmrRXGU5k6nJHdeQ"
  facebook = "https://www.facebook.com/Divag-227653670703371"
  discord = "https://discord.gg/YVtspERKch"
  


[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
